import { NextIntlClientProvider, useMessages } from "next-intl";

import { fiCenturyVariable, outfit } from "@/utils/fonts";
import "../globals.css";
import { ThemeModeScript } from "flowbite-react";
import NewsTopBar from "@/components/header/NewsTopBar";
import Navbar from "@/components/header/Navbar";
// import CatNavigation from "@/components/header/CatNavigation";
// import FooterSection from "@/components/footer/FooterSection";
// import MainHeaderTop from "@/components/header/MainHeader-Top";
// import MainHeader from "@/components/header/MainHeader";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
    const messages = useMessages();
    return (
        <html lang={locale}>
            <head>
                <ThemeModeScript />
            </head>
            <body className={outfit.className}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <div className="flex flex-col min-h-screen min-w-full items-start justify-start m-0 p-0">
                        <NewsTopBar />
                        <Navbar />
                        {/* <CatNavigation /> */}
                        {/* <MainHeaderTop /> */}
                        {/* <MainHeader /> */}
                        {/* <Header /> */}
                        {/* <Switcher /> */}
                        <p>{locale}</p>
                        {children}
                    </div>
                    {/* <FooterSection /> */}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
